### ISSUE TITLE
Question: How I can save a cropped image?

### ISSUE THREAD

**Issue by Proxi01** [wyhaya/react-crop-image#1]
I use your tool to crop user's profile photos. So, let's image that user select needed fragment on the photo and now he wants to save it. But I really can't understand how to save the cropped image?

**Comment by wyhaya** [comment]
@Proxi01 He only provides location information, you can use  `canvas` for cropping and saving.

```
1. Create a canvas tag and crop it with drawImage
// base64
2. canvas.toDataURL('image/png') 
// blob
3. Convert to a file using new Blob
```
I hope to help you
